sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dartardocker/docker-react.git -f Dockerfile.dev .
  
script:
  - docker run -e CI=true dartardocker/docker-react npm run test
